{
  nixos-wsl,
  lib,
  pkgs,
  myvars,
  ...
}:
{
  imports = [
    # NixOS-WSL 模块（wsl.enable / wsl.defaultUser 等）
    nixos-wsl.nixosModules.default
  ];

  wsl.enable = true;
  wsl.defaultUser = "vitus";

  networking.hostName = "hestia";

  environment.systemPackages = with pkgs; [
    gcc
    gnumake
    git
    python3
    nodejs # bb 服务运行时依赖
    tailscale # tailnet 节点（scale.scutosc.cn）
  ];

  programs.nix-ld.enable = true;

  # 用户 vitus 与仓库 vars 的用户体系保持一致（WSL 内终端使用）
  users.users.vitus = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    initialHashedPassword = myvars.initialHashedPassword;
    # 手机 Termux（oneplus-a0288f4a-to-computers）与各工作站免密登录 hestia
    openssh.authorizedKeys.keys = myvars.mainSshAuthorizedKeys;
  };

  # 手机/Tailnet 节点经 SSH 进入 WSL（2026-09-13，路径 A：hestia 直接入 tailnet）
  # WSL 位于 Windows NAT 后，eth0 无外部暴露；真正边界是 Windows 侧，故关防火墙。
  networking.firewall.enable = lib.mkForce false;

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  # Tailscale（headscale scale.scutosc.cn，与全盘各节点同一协调服务器）
  services.tailscale = {
    enable = true;
    openFirewall = true;
    extraSetFlags = [ "--accept-routes" ];
  };

  # 私有 flake 输入（mysecrets）通过该文件携带 GitHub token。
  # 文件本身不放仓库，由部署时手工写入 /etc/agenix/nix-access-tokens。
  nix.extraOptions = ''
    !include /etc/agenix/nix-access-tokens
  '';

  # bb - agentic IDE server (localhost:38886)
  # 原 WSL 配置以 nixos 用户运行；defaultUser 切到 vitus 后 nixos 用户已移除，
  # 因此改为以 vitus 运行，目录已从 /home/nixos/bb-app 迁到 /home/vitus/bb-app。
  systemd.services.bb = {
    description = "bb - agentic IDE server (localhost:38886)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    serviceConfig = {
      User = "vitus";
      WorkingDirectory = "/home/vitus/bb-app";
      ExecStart = "/home/vitus/bb-app/start.sh";
      Restart = "on-failure";
      RestartSec = 5;
    };
  };

  # hindsight - memory backend for omp (localhost:8888)
  # /etc/hindsight.env holds the LLM key and LD_LIBRARY_PATH; generated by
  # /home/vitus/hindsight/gen-env.sh (kept out of the repo to avoid secrets
  # in the nix store). Rerun that script after rebuilds if it goes missing.
  systemd.services.hindsight = {
    description = "Hindsight memory API for omp (localhost:8888)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    serviceConfig = {
      User = "vitus";
      Group = "users";
      WorkingDirectory = "/home/vitus/hindsight";
      ExecStart = "/home/vitus/hindsight/.venv/bin/hindsight-api --host 127.0.0.1 --port 8888";
      EnvironmentFile = "/etc/hindsight.env";
      Restart = "on-failure";
      RestartSec = 5;
    };
  };

  # NixOS root has no /usr/share/zoneinfo; the pg0 embedded PostgreSQL needs it.
  system.activationScripts.hindsightZoneinfo.text = ''
    mkdir -p /usr/share
    ln -sfn ${pkgs.tzdata}/share/zoneinfo /usr/share/zoneinfo
  '';

  system.stateVersion = "26.05";
}
