{ lib }:
{
  username = "vitus";
  githubUsername = "Vitus213";
  userfullname = "Vitus Apollo";
  useremail = "zhzvitus@gmail.com";
  networking = import ./networking.nix { inherit lib; };
  # generated by `mkpasswd -m yescrypt -s`
  # https://man.archlinux.org/man/crypt.5.en
  initialHashedPassword = "$y$j9T$La674kWPOC7pC3c9VU2TN.$iT75P2k7Z.AXDvRBJX9gESzOzF.q01kwWZfXZnGnYN.";
  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "ryan@xxx" -f ~/.ssh/xxx
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  mainSshAuthorizedKeys = [
    # The main ssh keys for daily usage
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFq9nvgrkiT+OQeyxeIgEOBHEE0y3OS4yxbV6OsdYlR5 vitus@5600"
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaKzP+PbGAhundgHlKsJ75420SAfXCGQdEUA8XWBU7mUV+aoXYSiYy8eAf0thrNF61hojw6WZ4agIRIM4bF2gH75Kjc2v4jwPNsVtC9VAQM6WXoikmpSFWDRL7R0T//Y7eQRP/sfPH4jGedakeHqucp3DKn1Vw6KnsgpLWfgY6MEQDgplj33JyiR3gYpiGVT082nGMOHSWqIf5cpkHFNa9zF0Nae3U3MNwoFyYtNjWxj/lGnn4AU6gdSW40UiBs6e2T2Lhb0tT2EANRab8p3r2X5EIMTeGCIr2yyhmBbILhGnkYI80sXMq53sXHrnteWnxnhpXTZ4UpHBUp+Ab2yk7ZmZU7671YiIe50UzbH3GR1JFLclvOJvxiOvTfCA3o15VSNGFKehwVBR0EoOiLY3nmBzrZNZ0tRDR/CeBePLU3HsPWPPeZmmGEUj1fO8CsHTHL9JdqFhV94IY5+yfycR7EHNEFh66SprV0n0YoHOUogyBjrUclUTcGef4yfe0XR0= VitusWsl"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPno/uSP9Aubo1zCQlZWDq2lif2MGHOTuY0fDnwv9AFY root@VitusMac"
    # v2 macbook (macOS, artemis) — 2026-08-28 confirmed key, distributed to all servers
    # NOTE: root@VitusMac above is an OLD different key; vitusartemis uses the line below
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHsJsNMjCqrCdB1dItRvB6pbDjbLwnPYlTmunAqcJX18 vitusartemis"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPXxlTTqqEIle9IHXImZggeobIekrqVdxvyzn52KTrs7 vitus@athena"
    # OnePlus 13T (PKX110), Termux, daily carry phone
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBXiRk7RVa7uV+v1PQKcpETytESuz8nH7lQbq/GpCJFT oneplus-a0288f4a-to-computers"
  ];
  secondaryAuthorizedKeys = [
    # the backup ssh keys for disaster recovery
    # "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMzYT0Fpcp681eHY5FJV2G8Mve53iX3hMOLGbVvfL+TF ryan@romantic"
  ];
}
