{ lib }:
{
  username = "vitus";
  userfullname = "Vitus Apollo";
  useremail = "zhzvitus@gmail.com";
  networking = import ./networking.nix { inherit lib; };
  # generated by `mkpasswd -m scrypt --rounds=11`
  # https://man.archlinux.org/man/crypt.5.en
  initialHashedPassword = "$7$GU..../....maCfhiALFSaHUQaDHjO5n/$88gtihyf0e/yuWHdhx.GV7NGcZ5qLdhcVf9ElPmvmu1";
  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "ryan@xxx" -f ~/.ssh/xxx
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  mainSshAuthorizedKeys = [
    # The main ssh keys for daily usage
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFq9nvgrkiT+OQeyxeIgEOBHEE0y3OS4yxbV6OsdYlR5 vitus@5600"
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaKzP+PbGAhundgHlKsJ75420SAfXCGQdEUA8XWBU7mUV+aoXYSiYy8eAf0thrNF61hojw6WZ4agIRIM4bF2gH75Kjc2v4jwPNsVtC9VAQM6WXoikmpSFWDRL7R0T//Y7eQRP/sfPH4jGedakeHqucp3DKn1Vw6KnsgpLWfgY6MEQDgplj33JyiR3gYpiGVT082nGMOHSWqIf5cpkHFNa9zF0Nae3U3MNwoFyYtNjWxj/lGnn4AU6gdSW40UiBs6e2T2Lhb0tT2EANRab8p3r2X5EIMTeGCIr2yyhmBbILhGnkYI80sXMq53sXHrnteWnxnhpXTZ4UpHBUp+Ab2yk7ZmZU7671YiIe50UzbH3GR1JFLclvOJvxiOvTfCA3o15VSNGFKehwVBR0EoOiLY3nmBzrZNZ0tRDR/CeBePLU3HsPWPPeZmmGEUj1fO8CsHTHL9JdqFhV94IY5+yfycR7EHNEFh66SprV0n0YoHOUogyBjrUclUTcGef4yfe0XR0= VitusWsl"
  ];
  secondaryAuthorizedKeys = [
    # the backup ssh keys for disaster recovery
    # "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMzYT0Fpcp681eHY5FJV2G8Mve53iX3hMOLGbVvfL+TF ryan@romantic"
  ];
}
