[Appearance]
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default
style=Fusion

[ColorScheme]
active\alternate_base=#11111B
active\base=#1E1E2E
active\button=#313244
active\button_text=#CDD6F4
active\bright_text=#F5C2E7
active\highlight=#F5C2E7
active\highlighted_text=#11111B
active\link=#F5C2E7
active\link_visited=#CBA6F7
active\placeholder_text=#A6ADC8
active\text=#CDD6F4
active\tooltip_base=#11111B
active\tooltip_text=#CDD6F4
active\window=#181825
active\window_text=#CDD6F4
disabled\base=#1E1E2E
disabled\button=#313244
disabled\button_text=#585B70
disabled\text=#585B70
disabled\window=#181825
disabled\window_text=#585B70
inactive\base=#1E1E2E
inactive\button=#313244
inactive\button_text=#BAC2DE
inactive\text=#BAC2DE
inactive\window=#181825
inactive\window_text=#BAC2DE
